server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  datasource:
    #使用mysql数据库，需要安装数据库
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  #使用h2数据库，不需要安装数据库
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:test;MODE=ORACLE;DB_CLOSE_DELAY=-1
  #    username: sa
  #    password:
  #    data: classpath:init.sql
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
